// US place data for location type-ahead and matching: 50 states + DC, tech metro areas, and US
// cities (roughly every city over 50k people plus well-known tech suburbs and neighborhoods that
// show up in job postings). Loaded lazily (lib/geo/index.ts `loadGeo`) so it isn't in the first
// page's bundle. Compact on purpose: cities are comma-separated names grouped by state.
//
// Metros follow the Census metro areas loosely, split where job seekers think of them separately
// (Orange County vs Los Angeles, Silicon Valley inside the SF Bay Area). A city belongs to at most
// one metro; a metro can include another (`includes`), so choosing the Bay Area also covers
// Silicon Valley cities.

export type StateRow = [code: string, name: string, aliases?: string[]];

export const STATES: StateRow[] = [
  ["AL", "Alabama", ["Ala"]],
  ["AK", "Alaska"],
  ["AZ", "Arizona", ["Ariz"]],
  ["AR", "Arkansas", ["Ark"]],
  ["CA", "California", ["Calif", "Cali"]],
  ["CO", "Colorado", ["Colo"]],
  ["CT", "Connecticut", ["Conn"]],
  ["DE", "Delaware"],
  ["DC", "District of Columbia"],
  ["FL", "Florida", ["Fla"]],
  ["GA", "Georgia"],
  ["HI", "Hawaii"],
  ["ID", "Idaho"],
  ["IL", "Illinois", ["Ill"]],
  ["IN", "Indiana", ["Ind"]],
  ["IA", "Iowa"],
  ["KS", "Kansas", ["Kan"]],
  ["KY", "Kentucky"],
  ["LA", "Louisiana"],
  ["ME", "Maine"],
  ["MD", "Maryland"],
  ["MA", "Massachusetts", ["Mass"]],
  ["MI", "Michigan", ["Mich"]],
  ["MN", "Minnesota", ["Minn"]],
  ["MS", "Mississippi"],
  ["MO", "Missouri"],
  ["MT", "Montana"],
  ["NE", "Nebraska"],
  ["NV", "Nevada"],
  ["NH", "New Hampshire"],
  ["NJ", "New Jersey"],
  ["NM", "New Mexico"],
  ["NY", "New York"],
  ["NC", "North Carolina"],
  ["ND", "North Dakota"],
  ["OH", "Ohio"],
  ["OK", "Oklahoma", ["Okla"]],
  ["OR", "Oregon"],
  ["PA", "Pennsylvania", ["Penn"]],
  ["RI", "Rhode Island"],
  ["SC", "South Carolina"],
  ["SD", "South Dakota"],
  ["TN", "Tennessee", ["Tenn"]],
  ["TX", "Texas", ["Tex"]],
  ["UT", "Utah"],
  ["VT", "Vermont"],
  ["VA", "Virginia"],
  ["WA", "Washington", ["Wash"]],
  ["WV", "West Virginia"],
  ["WI", "Wisconsin", ["Wis"]],
  ["WY", "Wyoming"],
];

export interface MetroRow {
  slug: string;
  name: string;
  /** States it spans; the first is its main state. */
  states: string[];
  aliases?: string[];
  /** Other metros inside this one (choosing this one covers their cities too). */
  includes?: string[];
  /** State code -> comma-separated city names. */
  cities: Record<string, string>;
}

export const METROS: MetroRow[] = [
  {
    slug: "nyc",
    name: "New York City area",
    states: ["NY", "NJ", "CT"],
    aliases: ["NYC", "New York City", "New York", "NY Metro", "New York Metro", "New York Metropolitan", "Greater New York", "Tri-State", "Tri-State Area", "New York City Metropolitan"],
    cities: {
      NY: "New York,Manhattan,Brooklyn,Queens,Bronx,The Bronx,Staten Island,Long Island City,Yonkers,New Rochelle,Mount Vernon,White Plains,Hempstead,Garden City,Mineola,Tarrytown,Purchase,Armonk,Rye,Hauppauge,Melville,Huntington,Islip,Hicksville,Levittown,Jericho,Port Washington,Great Neck,Valley Stream,Freeport,Long Beach,Sleepy Hollow,Harrison,Scarsdale,Brentwood,Central Islip,Ronkonkoma,Farmingdale,Bethpage,Uniondale,Lake Success",
      NJ: "Newark,Jersey City,Paterson,Elizabeth,Clifton,Passaic,Union City,Bayonne,East Orange,Hoboken,West New York,Hackensack,Fort Lee,Morristown,Parsippany,New Brunswick,Edison,Woodbridge,Iselin,Piscataway,Somerset,Bridgewater,Basking Ridge,Florham Park,Secaucus,Weehawken,Paramus,Montclair,Livingston,Red Bank,Holmdel,Toms River,Lakewood,Brick,Perth Amboy,Kearny,Linden,Plainfield,Sayreville,Old Bridge,Middletown,Union,North Bergen,Wayne,Irvington,Bloomfield,Harrison,Summit,Berkeley Heights,Murray Hill,Short Hills,Whippany,Mahwah,Rutherford,East Rutherford,Lyndhurst,Englewood Cliffs,Englewood,Teaneck,Rahway,Carteret,Metuchen,Matawan,Freehold",
      CT: "Stamford,Norwalk,Bridgeport,Greenwich,Danbury,Westport,Shelton,Fairfield,Trumbull,Darien,Wilton",
    },
  },
  {
    slug: "la",
    name: "Los Angeles area",
    states: ["CA"],
    aliases: ["LA", "L.A.", "Los Angeles", "Greater Los Angeles", "Los Angeles Metro", "Los Angeles Metropolitan", "LA Metro", "Los Angeles County", "LA County"],
    cities: {
      CA: "Los Angeles,Long Beach,Santa Clarita,Glendale,Lancaster,Palmdale,Pomona,Torrance,Pasadena,El Monte,Downey,Inglewood,West Covina,Norwalk,Burbank,Compton,South Gate,Carson,Santa Monica,Hawthorne,Whittier,Alhambra,Lakewood,Bellflower,Baldwin Park,Lynwood,Redondo Beach,Pico Rivera,Montebello,Monterey Park,Gardena,Huntington Park,Arcadia,Diamond Bar,Paramount,Rosemead,Glendora,Cerritos,La Mirada,Covina,Azusa,Rancho Palos Verdes,Culver City,West Hollywood,Beverly Hills,El Segundo,Manhattan Beach,Hermosa Beach,Calabasas,Agoura Hills,Westlake Village,Monrovia,Irwindale,San Gabriel,San Dimas,Claremont,La Verne,Walnut,Duarte,Sierra Madre,South Pasadena,La Canada Flintridge,Malibu,Lawndale,Signal Hill,Bell,Bell Gardens,Commerce,Vernon,Santa Fe Springs,Artesia,Lomita,Palos Verdes Estates,Rolling Hills Estates,Temple City,San Marino,City of Industry,La Puente,Hollywood,North Hollywood,Playa Vista,Playa del Rey,Marina del Rey,Venice,Westwood,Century City,Sherman Oaks,Studio City,Encino,Van Nuys,Woodland Hills,Chatsworth,Northridge,Canoga Park,Valencia,West Los Angeles,Silver Lake,Echo Park,Los Feliz,Koreatown,Boyle Heights,Highland Park,Eagle Rock,Mar Vista,Sawtelle,Brentwood Los Angeles,Pacific Palisades,Downtown Los Angeles,Arts District",
    },
  },
  {
    slug: "oc",
    name: "Orange County",
    states: ["CA"],
    aliases: ["OC", "Orange County", "Orange County Area"],
    cities: {
      CA: "Irvine,Anaheim,Santa Ana,Huntington Beach,Garden Grove,Fullerton,Orange,Costa Mesa,Mission Viejo,Westminster,Newport Beach,Buena Park,Lake Forest,Tustin,Yorba Linda,San Clemente,Laguna Niguel,La Habra,Fountain Valley,Placentia,Rancho Santa Margarita,Aliso Viejo,Cypress,Brea,Stanton,San Juan Capistrano,Dana Point,Laguna Hills,Seal Beach,Laguna Beach,Los Alamitos,La Palma,Villa Park,Laguna Woods,Ladera Ranch,Foothill Ranch,Coto de Caza,Irvine Spectrum",
    },
  },
  {
    slug: "sf-bay-area",
    name: "SF Bay Area",
    states: ["CA"],
    aliases: ["Bay Area", "SF Bay Area", "San Francisco Bay Area", "SF", "SFBA", "Greater San Francisco", "San Francisco Area", "San Francisco Bay", "SF Bay", "Greater Bay Area", "San Francisco Metro"],
    includes: ["silicon-valley"],
    cities: {
      CA: "San Francisco,Oakland,Berkeley,Fremont,Hayward,Daly City,San Mateo,South San Francisco,San Bruno,Burlingame,Foster City,Belmont,Millbrae,Pacifica,Brisbane,Half Moon Bay,Alameda,Emeryville,Albany,Piedmont,San Leandro,Castro Valley,Union City,Newark,Pleasanton,Livermore,Dublin,San Ramon,Danville,Walnut Creek,Concord,Pleasant Hill,Martinez,Lafayette,Orinda,Moraga,Richmond,El Cerrito,Hercules,Pinole,Antioch,Pittsburg,Brentwood,Vallejo,Fairfield,Vacaville,Benicia,Napa,Santa Rosa,Petaluma,San Rafael,Novato,Mill Valley,Sausalito,Larkspur,Corte Madera,Tiburon,Santa Cruz,Scotts Valley,Watsonville,Redwood Shores",
    },
  },
  {
    slug: "silicon-valley",
    name: "Silicon Valley",
    states: ["CA"],
    aliases: ["Silicon Valley", "San Jose Area", "Greater San Jose", "San Jose Metro", "Santa Clara Valley"],
    cities: {
      CA: "San Jose,Santa Clara,Sunnyvale,Mountain View,Palo Alto,Cupertino,Milpitas,Los Gatos,Los Altos,Los Altos Hills,Campbell,Saratoga,Morgan Hill,Gilroy,Menlo Park,East Palo Alto,Redwood City,San Carlos,Atherton,Woodside,Portola Valley,Stanford,Monte Sereno,Alviso",
    },
  },
  {
    slug: "san-diego",
    name: "San Diego area",
    states: ["CA"],
    aliases: ["San Diego", "Greater San Diego", "San Diego County", "San Diego Metro"],
    cities: {
      CA: "San Diego,Chula Vista,Oceanside,Escondido,Carlsbad,El Cajon,Vista,San Marcos,Encinitas,National City,La Mesa,Santee,Poway,Del Mar,Solana Beach,Coronado,Imperial Beach,Lemon Grove,La Jolla,Rancho Bernardo,Sorrento Valley,Carmel Valley,Mira Mesa,Rancho Santa Fe,Spring Valley",
    },
  },
  {
    slug: "inland-empire",
    name: "Inland Empire",
    states: ["CA"],
    aliases: ["Inland Empire", "IE", "Riverside-San Bernardino", "Riverside County", "San Bernardino County"],
    cities: {
      CA: "Riverside,San Bernardino,Fontana,Moreno Valley,Rancho Cucamonga,Ontario,Corona,Victorville,Murrieta,Temecula,Jurupa Valley,Menifee,Chino,Chino Hills,Upland,Redlands,Hemet,Indio,Rialto,Hesperia,Perris,Eastvale,Colton,Highland,Lake Elsinore,Apple Valley,Palm Desert,Palm Springs,Cathedral City,Beaumont,Yucaipa,Montclair,Loma Linda,Norco,Coachella,La Quinta,Banning,Adelanto,Grand Terrace",
    },
  },
  {
    slug: "sacramento",
    name: "Sacramento area",
    states: ["CA"],
    aliases: ["Sacramento", "Greater Sacramento", "Sacramento Metro"],
    cities: { CA: "Sacramento,Elk Grove,Roseville,Folsom,Citrus Heights,Rancho Cordova,Davis,West Sacramento,Rocklin,Woodland,Lincoln,El Dorado Hills,Arden-Arcade,Carmichael" },
  },
  {
    slug: "ventura",
    name: "Ventura County",
    states: ["CA"],
    aliases: ["Ventura County", "Oxnard-Thousand Oaks", "Conejo Valley"],
    cities: { CA: "Oxnard,Thousand Oaks,Simi Valley,Ventura,Camarillo,Moorpark,Newbury Park,Port Hueneme,Santa Paula,Ojai,Fillmore" },
  },
  {
    slug: "santa-barbara",
    name: "Santa Barbara area",
    states: ["CA"],
    aliases: ["Santa Barbara", "Santa Barbara County"],
    cities: { CA: "Santa Barbara,Goleta,Santa Maria,Lompoc,Carpinteria" },
  },
  {
    slug: "fresno",
    name: "Fresno area",
    states: ["CA"],
    aliases: ["Fresno", "Central Valley"],
    cities: { CA: "Fresno,Clovis,Madera" },
  },
  {
    slug: "seattle",
    name: "Seattle area",
    states: ["WA"],
    aliases: ["Seattle", "Greater Seattle", "Seattle Area", "Seattle Metro", "Puget Sound", "Eastside", "Seattle-Tacoma"],
    cities: {
      WA: "Seattle,Bellevue,Redmond,Kirkland,Tacoma,Everett,Kent,Renton,Federal Way,Auburn,Bothell,Issaquah,Sammamish,Lynnwood,Shoreline,Burien,Lakewood,Marysville,Edmonds,Puyallup,SeaTac,Tukwila,Woodinville,Mercer Island,Kenmore,Mukilteo,Lake Stevens,Des Moines,University Place,Mill Creek,Maple Valley,Covington,Snoqualmie,Bonney Lake,Gig Harbor,Mountlake Terrace,Lake Forest Park",
    },
  },
  {
    slug: "portland",
    name: "Portland area",
    states: ["OR", "WA"],
    aliases: ["Portland", "Portland Metro", "Greater Portland", "PDX", "Silicon Forest"],
    cities: {
      OR: "Portland,Beaverton,Hillsboro,Gresham,Lake Oswego,Tigard,Tualatin,Wilsonville,Oregon City,West Linn,Happy Valley,Milwaukie,Sherwood,Forest Grove,Troutdale,Canby",
      WA: "Vancouver,Camas,Battle Ground,Washougal",
    },
  },
  {
    slug: "spokane",
    name: "Spokane area",
    states: ["WA", "ID"],
    aliases: ["Spokane", "Inland Northwest"],
    cities: { WA: "Spokane,Spokane Valley,Liberty Lake,Cheney", ID: "Coeur d'Alene,Post Falls" },
  },
  {
    slug: "boise",
    name: "Boise area",
    states: ["ID"],
    aliases: ["Boise", "Treasure Valley"],
    cities: { ID: "Boise,Meridian,Nampa,Caldwell,Eagle,Kuna,Star" },
  },
  {
    slug: "salt-lake-city",
    name: "Salt Lake City area",
    states: ["UT"],
    aliases: ["Salt Lake City", "SLC", "Salt Lake", "Greater Salt Lake", "Wasatch Front"],
    cities: {
      UT: "Salt Lake City,West Valley City,West Jordan,Sandy,South Jordan,Murray,Taylorsville,Draper,Riverton,Herriman,Midvale,Cottonwood Heights,Holladay,Millcreek,South Salt Lake,Bluffdale,Kearns,Magna",
    },
  },
  {
    slug: "provo",
    name: "Provo / Lehi area",
    states: ["UT"],
    aliases: ["Provo", "Silicon Slopes", "Utah County", "Provo-Orem"],
    cities: { UT: "Provo,Orem,Lehi,American Fork,Pleasant Grove,Spanish Fork,Springville,Saratoga Springs,Eagle Mountain,Lindon,Vineyard,Payson,Highland,Alpine,Cedar Hills,Mapleton" },
  },
  {
    slug: "ogden",
    name: "Ogden area",
    states: ["UT"],
    aliases: ["Ogden"],
    cities: { UT: "Ogden,Layton,Clearfield,Kaysville,Bountiful,Roy,Farmington,Syracuse,Centerville,Clinton" },
  },
  {
    slug: "denver",
    name: "Denver area",
    states: ["CO"],
    aliases: ["Denver", "Greater Denver", "Denver Metro", "Denver Area", "Front Range"],
    cities: {
      CO: "Denver,Aurora,Lakewood,Thornton,Arvada,Westminster,Centennial,Highlands Ranch,Littleton,Englewood,Greenwood Village,Broomfield,Parker,Castle Rock,Commerce City,Brighton,Northglenn,Lone Tree,Golden,Wheat Ridge,Ken Caryl,Federal Heights,Castle Pines,Denver Tech Center",
    },
  },
  {
    slug: "boulder",
    name: "Boulder area",
    states: ["CO"],
    aliases: ["Boulder", "Boulder County"],
    cities: { CO: "Boulder,Longmont,Louisville,Lafayette,Superior,Erie" },
  },
  {
    slug: "colorado-springs",
    name: "Colorado Springs area",
    states: ["CO"],
    aliases: ["Colorado Springs"],
    cities: { CO: "Colorado Springs,Fountain,Monument,Security-Widefield" },
  },
  {
    slug: "fort-collins",
    name: "Fort Collins area",
    states: ["CO"],
    aliases: ["Fort Collins", "Northern Colorado", "NoCo"],
    cities: { CO: "Fort Collins,Loveland,Windsor,Greeley" },
  },
  {
    slug: "phoenix",
    name: "Phoenix area",
    states: ["AZ"],
    aliases: ["Phoenix", "Greater Phoenix", "Phoenix Metro", "Valley of the Sun", "Metro Phoenix"],
    cities: {
      AZ: "Phoenix,Mesa,Chandler,Scottsdale,Gilbert,Glendale,Tempe,Peoria,Surprise,Avondale,Goodyear,Buckeye,Queen Creek,Maricopa,Casa Grande,Fountain Hills,Paradise Valley,Cave Creek,Apache Junction,San Tan Valley,Sun City,Litchfield Park,Tolleson,El Mirage,Anthem",
    },
  },
  {
    slug: "tucson",
    name: "Tucson area",
    states: ["AZ"],
    aliases: ["Tucson"],
    cities: { AZ: "Tucson,Marana,Oro Valley,Sahuarita,Catalina Foothills" },
  },
  {
    slug: "las-vegas",
    name: "Las Vegas area",
    states: ["NV"],
    aliases: ["Las Vegas", "Vegas", "Las Vegas Valley"],
    cities: { NV: "Las Vegas,Henderson,North Las Vegas,Paradise,Enterprise,Spring Valley,Summerlin,Sunrise Manor,Whitney,Boulder City" },
  },
  {
    slug: "reno",
    name: "Reno area",
    states: ["NV"],
    aliases: ["Reno", "Reno-Sparks", "Reno-Tahoe"],
    cities: { NV: "Reno,Sparks,Carson City" },
  },
  {
    slug: "albuquerque",
    name: "Albuquerque area",
    states: ["NM"],
    aliases: ["Albuquerque", "ABQ"],
    cities: { NM: "Albuquerque,Rio Rancho,Los Lunas,Kirtland AFB" },
  },
  {
    slug: "dfw",
    name: "Dallas-Fort Worth",
    states: ["TX"],
    aliases: ["DFW", "Dallas-Fort Worth", "Dallas Fort Worth", "Dallas/Fort Worth", "Metroplex", "Dallas Area", "Greater Dallas", "Dallas Metro", "North Texas"],
    cities: {
      TX: "Dallas,Fort Worth,Arlington,Plano,Irving,Garland,Frisco,McKinney,Grand Prairie,Denton,Mesquite,Carrollton,Richardson,Lewisville,Allen,Flower Mound,North Richland Hills,Mansfield,Rowlett,Euless,DeSoto,Grapevine,Bedford,Cedar Hill,Wylie,Keller,Coppell,Rockwall,Southlake,Addison,Farmers Branch,The Colony,Little Elm,Prosper,Haltom City,Hurst,Burleson,Duncanville,Lancaster,Westlake,Weatherford,Colleyville,Las Colinas,University Park,Highland Park,Sachse,Murphy,Celina,Forney,Waxahachie,Midlothian,Trophy Club,Roanoke",
    },
  },
  {
    slug: "houston",
    name: "Houston area",
    states: ["TX"],
    aliases: ["Houston", "Greater Houston", "Houston Metro", "Houston Area"],
    cities: {
      TX: "Houston,Pasadena,The Woodlands,Sugar Land,Pearland,League City,Baytown,Conroe,Missouri City,Katy,Spring,Cypress,Humble,Friendswood,Tomball,Galveston,Richmond,Rosenberg,Atascocita,Stafford,Bellaire,Kingwood,Clear Lake,Webster,Deer Park,Texas City,La Porte,Channelview,Mission Bend,Fulshear",
    },
  },
  {
    slug: "austin",
    name: "Austin area",
    states: ["TX"],
    aliases: ["Austin", "Greater Austin", "Austin Metro", "Austin Area", "Silicon Hills"],
    cities: { TX: "Austin,Round Rock,Cedar Park,Georgetown,Pflugerville,San Marcos,Leander,Kyle,Buda,Hutto,Lakeway,Bee Cave,Manor,Liberty Hill,Dripping Springs,West Lake Hills" },
  },
  {
    slug: "san-antonio",
    name: "San Antonio area",
    states: ["TX"],
    aliases: ["San Antonio", "Greater San Antonio", "San Antonio Metro"],
    cities: { TX: "San Antonio,New Braunfels,Schertz,Converse,Boerne,Seguin,Universal City,Live Oak,Helotes,Cibolo" },
  },
  {
    slug: "el-paso",
    name: "El Paso area",
    states: ["TX"],
    aliases: ["El Paso"],
    cities: { TX: "El Paso,Socorro,Horizon City" },
  },
  {
    slug: "chicago",
    name: "Chicago area",
    states: ["IL", "IN", "WI"],
    aliases: ["Chicago", "Chicagoland", "Greater Chicago", "Chicago Metro", "Chicago Area"],
    cities: {
      IL: "Chicago,Aurora,Naperville,Joliet,Elgin,Waukegan,Cicero,Schaumburg,Evanston,Arlington Heights,Bolingbrook,Palatine,Skokie,Des Plaines,Orland Park,Tinley Park,Oak Lawn,Berwyn,Mount Prospect,Wheaton,Downers Grove,Oak Park,Glenview,Hoffman Estates,Lombard,Elmhurst,Buffalo Grove,Northbrook,Deerfield,Lake Forest,Oak Brook,Rosemont,Itasca,Lisle,Warrenville,Vernon Hills,Libertyville,Highland Park,Park Ridge,Wilmette,Plainfield,Romeoville,Carol Stream,Bartlett,Streamwood,St. Charles,Batavia,Geneva,Crystal Lake,Gurnee,North Chicago,Lincolnshire,Oswego,Algonquin,Carpentersville,Glen Ellyn,Addison,Westmont,Woodridge,Burr Ridge,Oakbrook Terrace,Rolling Meadows,Elk Grove Village,Wheeling,Niles,Morton Grove,Calumet City,Chicago Heights,Harvey,Lockport,Mundelein,Riverwoods,Northfield",
      IN: "Gary,Hammond,Merrillville,Valparaiso,Portage,Crown Point,Schererville,Munster,East Chicago",
      WI: "Kenosha",
    },
  },
  {
    slug: "boston",
    name: "Boston area",
    states: ["MA", "NH"],
    aliases: ["Boston", "Greater Boston", "Boston Area", "Boston Metro", "Route 128"],
    cities: {
      MA: "Boston,Cambridge,Somerville,Waltham,Newton,Quincy,Lynn,Brockton,Framingham,Burlington,Lexington,Woburn,Bedford,Needham,Wellesley,Watertown,Medford,Malden,Brookline,Andover,North Andover,Lowell,Lawrence,Marlborough,Natick,Maynard,Chelmsford,Billerica,Wilmington,Westborough,Canton,Braintree,Weymouth,Revere,Peabody,Salem,Beverly,Haverhill,Methuen,Dedham,Norwood,Everett,Chelsea,Arlington,Belmont,Winchester,Reading,Wakefield,Stoneham,Melrose,Danvers,Tewksbury,Acton,Concord,Boxborough,Littleton,Hopkinton,Southborough,Milford,Franklin,Mansfield,Foxborough,Taunton,Plymouth,Marshfield,Hingham,Milton,Dorchester,Allston,Brighton,Charlestown,Roxbury,Jamaica Plain,Kendall Square",
      NH: "Nashua,Manchester,Portsmouth,Salem,Dover,Concord,Derry,Merrimack,Londonderry,Bedford,Hudson,Rochester",
    },
  },
  {
    slug: "worcester",
    name: "Worcester area",
    states: ["MA"],
    aliases: ["Worcester", "Central Massachusetts"],
    cities: { MA: "Worcester,Shrewsbury,Leominster,Fitchburg,Auburn,Northborough,Grafton" },
  },
  {
    slug: "providence",
    name: "Providence area",
    states: ["RI", "MA"],
    aliases: ["Providence", "Greater Providence"],
    cities: { RI: "Providence,Warwick,Cranston,Pawtucket,East Providence,Woonsocket,Coventry,Cumberland,North Providence,Johnston,Newport", MA: "Fall River,New Bedford,Attleboro,North Attleborough" },
  },
  {
    slug: "hartford",
    name: "Hartford area",
    states: ["CT"],
    aliases: ["Hartford", "Greater Hartford"],
    cities: { CT: "Hartford,West Hartford,East Hartford,New Britain,Bristol,Manchester,Glastonbury,Farmington,Windsor,Enfield,Southington,Wethersfield,Newington,Middletown,Rocky Hill,Simsbury" },
  },
  {
    slug: "new-haven",
    name: "New Haven area",
    states: ["CT"],
    aliases: ["New Haven"],
    cities: { CT: "New Haven,Waterbury,Meriden,West Haven,Milford,Hamden,Wallingford,Branford,North Haven" },
  },
  {
    slug: "philadelphia",
    name: "Philadelphia area",
    states: ["PA", "NJ", "DE", "MD"],
    aliases: ["Philadelphia", "Philly", "Greater Philadelphia", "Philadelphia Metro", "Delaware Valley"],
    cities: {
      PA: "Philadelphia,King of Prussia,Conshohocken,Malvern,Wayne,Radnor,Norristown,Chester,Horsham,Blue Bell,Fort Washington,Plymouth Meeting,West Chester,Media,Bryn Mawr,Exton,Bensalem,Levittown,Doylestown,Warminster,Lansdale,Newtown Square,Berwyn,Ardmore,Upper Darby,Collegeville",
      NJ: "Camden,Cherry Hill,Mount Laurel,Moorestown,Marlton,Voorhees,Vineland,Princeton,Trenton,Ewing,Lawrenceville,Hamilton,Plainsboro,West Windsor,Pennington",
      DE: "Wilmington,Newark,Dover,Middletown,New Castle",
      MD: "Elkton",
    },
  },
  {
    slug: "pittsburgh",
    name: "Pittsburgh area",
    states: ["PA"],
    aliases: ["Pittsburgh", "Greater Pittsburgh", "Pittsburgh Metro"],
    cities: { PA: "Pittsburgh,Cranberry Township,Canonsburg,Monroeville,Bethel Park,McKeesport,Wexford,Sewickley,Coraopolis,Moon Township,Mount Lebanon,Robinson Township,Greensburg,Warrendale,Carnegie" },
  },
  {
    slug: "lehigh-valley",
    name: "Lehigh Valley",
    states: ["PA", "NJ"],
    aliases: ["Lehigh Valley", "Allentown-Bethlehem"],
    cities: { PA: "Allentown,Bethlehem,Easton,Whitehall,Emmaus", NJ: "Phillipsburg" },
  },
  {
    slug: "dc",
    name: "Washington, DC area",
    states: ["DC", "MD", "VA", "WV"],
    aliases: ["DC", "D.C.", "DMV", "Washington DC", "Washington D.C.", "Washington Metro", "Greater Washington", "DC Metro", "DC Area", "Washington Area", "Northern Virginia", "NoVA", "National Capital Region"],
    cities: {
      DC: "Washington",
      VA: "Arlington,Alexandria,Reston,Herndon,McLean,Tysons,Tysons Corner,Fairfax,Falls Church,Vienna,Chantilly,Ashburn,Sterling,Leesburg,Manassas,Woodbridge,Springfield,Annandale,Centreville,Dulles,Burke,Lorton,Dale City,Fredericksburg,Stafford,Gainesville,Haymarket,Crystal City,Rosslyn,Ballston,Lansdowne,South Riding",
      MD: "Bethesda,Rockville,Silver Spring,Gaithersburg,Germantown,College Park,Bowie,Greenbelt,Laurel,Frederick,Hyattsville,Largo,Chevy Chase,Potomac,North Bethesda,Wheaton,Olney,Upper Marlboro,Lanham,Beltsville,Waldorf,Clarksburg,Landover,Oxon Hill,National Harbor,Suitland,Andrews AFB,Fort Detrick",
      WV: "Martinsburg,Harpers Ferry",
    },
  },
  {
    slug: "baltimore",
    name: "Baltimore area",
    states: ["MD"],
    aliases: ["Baltimore", "Greater Baltimore", "Baltimore Metro"],
    cities: { MD: "Baltimore,Columbia,Towson,Ellicott City,Annapolis,Glen Burnie,Owings Mills,Hunt Valley,Linthicum,Linthicum Heights,Fort Meade,Hanover,Annapolis Junction,Aberdeen,Aberdeen Proving Ground,Catonsville,Dundalk,Bel Air,Odenton,Severn,Pikesville,Timonium,Cockeysville,Sparks,Westminster,Elkridge,Halethorpe,Middle River,Essex,Parkville,Randallstown,Reisterstown,Crofton" },
  },
  {
    slug: "richmond",
    name: "Richmond area",
    states: ["VA"],
    aliases: ["Richmond", "Greater Richmond", "RVA"],
    cities: { VA: "Richmond,Glen Allen,Henrico,Midlothian,Chesterfield,Mechanicsville,Short Pump,Petersburg,Colonial Heights,Ashland" },
  },
  {
    slug: "hampton-roads",
    name: "Hampton Roads",
    states: ["VA", "NC"],
    aliases: ["Hampton Roads", "Tidewater", "Norfolk-Virginia Beach", "757"],
    cities: { VA: "Virginia Beach,Norfolk,Chesapeake,Newport News,Hampton,Portsmouth,Suffolk,Williamsburg,Yorktown,Poquoson", NC: "Elizabeth City" },
  },
  {
    slug: "raleigh-durham",
    name: "Raleigh-Durham (Research Triangle)",
    states: ["NC"],
    aliases: ["Research Triangle", "RTP", "Triangle", "The Triangle", "Raleigh-Durham", "Raleigh Durham", "Raleigh", "Durham", "Research Triangle Park", "Triangle Area", "Raleigh-Durham-Chapel Hill"],
    cities: { NC: "Raleigh,Durham,Cary,Chapel Hill,Morrisville,Apex,Wake Forest,Holly Springs,Fuquay-Varina,Research Triangle Park,Garner,Knightdale,Carrboro,Hillsborough,Wendell,Clayton,Rolesville,Zebulon" },
  },
  {
    slug: "charlotte",
    name: "Charlotte area",
    states: ["NC", "SC"],
    aliases: ["Charlotte", "Greater Charlotte", "Charlotte Metro", "Queen City"],
    cities: { NC: "Charlotte,Concord,Gastonia,Huntersville,Matthews,Mooresville,Cornelius,Kannapolis,Mint Hill,Davidson,Indian Trail,Monroe,Pineville,Harrisburg,Waxhaw", SC: "Rock Hill,Fort Mill,Indian Land,Tega Cay,Lancaster" },
  },
  {
    slug: "piedmont-triad",
    name: "Piedmont Triad",
    states: ["NC"],
    aliases: ["Piedmont Triad", "Triad", "Greensboro-Winston-Salem"],
    cities: { NC: "Greensboro,Winston-Salem,High Point,Burlington,Kernersville,Thomasville" },
  },
  {
    slug: "charleston-sc",
    name: "Charleston, SC area",
    states: ["SC"],
    aliases: ["Charleston SC", "Lowcountry"],
    cities: { SC: "Charleston,North Charleston,Mount Pleasant,Summerville,Goose Creek,Hanahan,Daniel Island" },
  },
  {
    slug: "greenville-sc",
    name: "Greenville-Spartanburg",
    states: ["SC"],
    aliases: ["Greenville-Spartanburg", "Upstate South Carolina", "Upstate SC"],
    cities: { SC: "Greenville,Spartanburg,Greer,Anderson,Mauldin,Simpsonville,Easley" },
  },
  {
    slug: "columbia-sc",
    name: "Columbia, SC area",
    states: ["SC"],
    aliases: ["Columbia SC", "Midlands"],
    cities: { SC: "Columbia,West Columbia,Lexington,Irmo,Cayce" },
  },
  {
    slug: "atlanta",
    name: "Atlanta area",
    states: ["GA"],
    aliases: ["Atlanta", "ATL", "Greater Atlanta", "Metro Atlanta", "Atlanta Metro", "Atlanta Area"],
    cities: {
      GA: "Atlanta,Alpharetta,Sandy Springs,Roswell,Johns Creek,Marietta,Smyrna,Duluth,Norcross,Dunwoody,Peachtree Corners,Kennesaw,Lawrenceville,Decatur,Brookhaven,Milton,Cumming,Suwanee,Buford,Stockbridge,Peachtree City,Newnan,East Point,College Park,Chamblee,Tucker,Woodstock,Canton,Douglasville,Snellville,Conyers,McDonough,Mableton,South Fulton,Stonecrest,Fayetteville,Acworth,Lilburn,Doraville,Midtown Atlanta,Buckhead",
    },
  },
  {
    slug: "miami",
    name: "Miami / South Florida",
    states: ["FL"],
    aliases: ["Miami", "South Florida", "Greater Miami", "Miami-Dade", "Miami Metro", "Miami-Fort Lauderdale", "SoFlo", "Broward", "Palm Beach County"],
    cities: {
      FL: "Miami,Fort Lauderdale,West Palm Beach,Hialeah,Hollywood,Pembroke Pines,Miramar,Coral Springs,Miami Gardens,Pompano Beach,Davie,Miami Beach,Plantation,Sunrise,Boca Raton,Deerfield Beach,Delray Beach,Boynton Beach,Jupiter,Palm Beach Gardens,Doral,Coral Gables,Weston,Homestead,Aventura,Kendall,Wellington,Lauderhill,Tamarac,Margate,North Miami,North Miami Beach,Cutler Bay,Palmetto Bay,Hallandale Beach,Dania Beach,Oakland Park,Coconut Creek,Parkland,Lake Worth Beach,Royal Palm Beach,Palm Beach,Brickell,Wynwood,Sweetwater,Fontainebleau",
    },
  },
  {
    slug: "tampa",
    name: "Tampa Bay area",
    states: ["FL"],
    aliases: ["Tampa", "Tampa Bay", "Tampa Bay Area", "Greater Tampa", "Tampa-St. Petersburg"],
    cities: { FL: "Tampa,St. Petersburg,Clearwater,Brandon,Largo,Wesley Chapel,Palm Harbor,Riverview,Plant City,Spring Hill,Dunedin,Oldsmar,Lutz,Land O' Lakes,Tarpon Springs,Pinellas Park,Seminole,New Port Richey,Temple Terrace,Apollo Beach" },
  },
  {
    slug: "orlando",
    name: "Orlando area",
    states: ["FL"],
    aliases: ["Orlando", "Greater Orlando", "Central Florida", "Orlando Metro"],
    cities: { FL: "Orlando,Kissimmee,Sanford,Lake Mary,Winter Park,Altamonte Springs,Oviedo,Apopka,Winter Garden,Clermont,Maitland,Ocoee,Winter Springs,Longwood,Casselberry,St. Cloud,Celebration,Lake Nona,Heathrow" },
  },
  {
    slug: "jacksonville",
    name: "Jacksonville area",
    states: ["FL"],
    aliases: ["Jacksonville", "Jax", "Greater Jacksonville", "Northeast Florida"],
    cities: { FL: "Jacksonville,Jacksonville Beach,Ponte Vedra Beach,St. Augustine,Orange Park,Fernandina Beach,Fleming Island,Atlantic Beach,Neptune Beach" },
  },
  {
    slug: "minneapolis",
    name: "Minneapolis-St. Paul (Twin Cities)",
    states: ["MN", "WI"],
    aliases: ["Twin Cities", "Minneapolis-St. Paul", "Minneapolis St Paul", "MSP", "Minneapolis", "Greater Minneapolis", "Minneapolis Metro"],
    cities: {
      MN: "Minneapolis,St. Paul,Bloomington,Brooklyn Park,Plymouth,Maple Grove,Woodbury,Eden Prairie,Eagan,Burnsville,Lakeville,Minnetonka,Edina,St. Louis Park,Blaine,Coon Rapids,Apple Valley,Roseville,Shakopee,Maplewood,Richfield,Hopkins,Golden Valley,Arden Hills,Cottage Grove,Inver Grove Heights,Brooklyn Center,Fridley,Andover,Savage,Prior Lake,Chanhassen,Chaska,Shoreview,New Brighton,Oakdale,Inver Grove,Mendota Heights,Wayzata,Anoka,Ramsey,Elk River,Rosemount,Farmington",
      WI: "Hudson,River Falls",
    },
  },
  {
    slug: "detroit",
    name: "Detroit area",
    states: ["MI"],
    aliases: ["Detroit", "Metro Detroit", "Greater Detroit", "Detroit Metro"],
    cities: {
      MI: "Detroit,Warren,Sterling Heights,Dearborn,Livonia,Troy,Farmington Hills,Southfield,Novi,Rochester Hills,Pontiac,Auburn Hills,Royal Oak,Canton,Westland,Taylor,Shelby Township,Clinton Township,Dearborn Heights,St. Clair Shores,Birmingham,Bloomfield Hills,Macomb,Waterford,West Bloomfield,Northville,Plymouth,Wixom,Madison Heights,Ferndale,Roseville,Romulus,Allen Park,Southgate,Wyandotte,Lincoln Park,Hamtramck,Grosse Pointe,Chesterfield,Commerce Township,Lake Orion,Orion Township,Bloomfield Township,Highland Park",
    },
  },
  {
    slug: "ann-arbor",
    name: "Ann Arbor area",
    states: ["MI"],
    aliases: ["Ann Arbor", "Washtenaw County"],
    cities: { MI: "Ann Arbor,Ypsilanti,Saline,Dexter,Chelsea" },
  },
  {
    slug: "grand-rapids",
    name: "Grand Rapids area",
    states: ["MI"],
    aliases: ["Grand Rapids", "West Michigan"],
    cities: { MI: "Grand Rapids,Wyoming,Kentwood,Holland,Walker,Grandville,Grand Haven,Byron Center,Ada,Rockford,Jenison" },
  },
  {
    slug: "lansing",
    name: "Lansing area",
    states: ["MI"],
    aliases: ["Lansing", "Greater Lansing"],
    cities: { MI: "Lansing,East Lansing,Okemos,Delta Township,Meridian Township" },
  },
  {
    slug: "columbus",
    name: "Columbus, OH area",
    states: ["OH"],
    aliases: ["Columbus", "Columbus OH", "Greater Columbus", "Central Ohio", "Columbus Metro"],
    cities: { OH: "Columbus,Dublin,Westerville,Worthington,Hilliard,Grove City,Upper Arlington,New Albany,Gahanna,Reynoldsburg,Delaware,Powell,Lewis Center,Pickerington,Groveport,Marysville,Newark,Lancaster,Plain City,Canal Winchester,Bexley,Whitehall,Obetz" },
  },
  {
    slug: "cleveland",
    name: "Cleveland area",
    states: ["OH"],
    aliases: ["Cleveland", "Greater Cleveland", "Northeast Ohio", "NEO"],
    cities: { OH: "Cleveland,Parma,Lakewood,Euclid,Mentor,Cleveland Heights,Strongsville,Westlake,Beachwood,Independence,Mayfield Heights,Solon,Elyria,Lorain,North Olmsted,North Royalton,Brunswick,Medina,Twinsburg,Brecksville,Shaker Heights,Garfield Heights,Middleburg Heights,Mayfield Village,Highland Heights,Berea,Avon,Avon Lake,Warrensville Heights,Seven Hills,Broadview Heights" },
  },
  {
    slug: "cincinnati",
    name: "Cincinnati area",
    states: ["OH", "KY", "IN"],
    aliases: ["Cincinnati", "Greater Cincinnati", "Cincy", "Cincinnati Metro", "Northern Kentucky"],
    cities: { OH: "Cincinnati,Mason,West Chester,Blue Ash,Fairfield,Hamilton,Middletown,Sharonville,Loveland,Milford,Norwood,Lebanon,Evendale,Liberty Township,Montgomery,Springdale", KY: "Covington,Florence,Newport,Erlanger,Independence,Fort Mitchell,Hebron,Union", IN: "Lawrenceburg" },
  },
  {
    slug: "dayton",
    name: "Dayton area",
    states: ["OH"],
    aliases: ["Dayton", "Greater Dayton", "Miami Valley"],
    cities: { OH: "Dayton,Kettering,Beavercreek,Huber Heights,Fairborn,Centerville,Miamisburg,Xenia,Vandalia,Springboro,Wright-Patterson AFB,Wright-Patterson Air Force Base" },
  },
  {
    slug: "akron",
    name: "Akron area",
    states: ["OH"],
    aliases: ["Akron"],
    cities: { OH: "Akron,Cuyahoga Falls,Stow,Hudson,Kent,Barberton,Green,Fairlawn,Tallmadge" },
  },
  {
    slug: "toledo",
    name: "Toledo area",
    states: ["OH"],
    aliases: ["Toledo"],
    cities: { OH: "Toledo,Perrysburg,Maumee,Sylvania,Bowling Green,Oregon" },
  },
  {
    slug: "indianapolis",
    name: "Indianapolis area",
    states: ["IN"],
    aliases: ["Indianapolis", "Indy", "Greater Indianapolis", "Indianapolis Metro", "Central Indiana"],
    cities: { IN: "Indianapolis,Carmel,Fishers,Noblesville,Westfield,Greenwood,Lawrence,Zionsville,Plainfield,Avon,Anderson,Brownsburg,Franklin,Greenfield,Speedway,Beech Grove,Whitestown,McCordsville" },
  },
  {
    slug: "milwaukee",
    name: "Milwaukee area",
    states: ["WI"],
    aliases: ["Milwaukee", "Greater Milwaukee", "Milwaukee Metro"],
    cities: { WI: "Milwaukee,Waukesha,West Allis,Wauwatosa,Brookfield,Menomonee Falls,New Berlin,Racine,Oak Creek,Pewaukee,Franklin,Greenfield,Mequon,Germantown,Cudahy,South Milwaukee,Glendale,Muskego,Oconomowoc,West Bend,Cedarburg,Delafield" },
  },
  {
    slug: "madison",
    name: "Madison area",
    states: ["WI"],
    aliases: ["Madison", "Greater Madison", "Madison WI"],
    cities: { WI: "Madison,Middleton,Sun Prairie,Fitchburg,Verona,Monona,Waunakee,Stoughton,DeForest" },
  },
  {
    slug: "st-louis",
    name: "St. Louis area",
    states: ["MO", "IL"],
    aliases: ["St. Louis", "Saint Louis", "STL", "Greater St. Louis", "St. Louis Metro"],
    cities: {
      MO: "St. Louis,St. Charles,St. Peters,O'Fallon,Chesterfield,Clayton,Creve Coeur,Florissant,Maryland Heights,Kirkwood,Town and Country,Ballwin,Wentzville,Wildwood,University City,Webster Groves,Hazelwood,Earth City,Fenton,Brentwood,Ladue,Arnold,Des Peres,Manchester,Bridgeton",
      IL: "Belleville,Edwardsville,O'Fallon,Collinsville,Granite City,Alton,Scott AFB,Scott Air Force Base,Shiloh",
    },
  },
  {
    slug: "kansas-city",
    name: "Kansas City area",
    states: ["MO", "KS"],
    aliases: ["Kansas City", "KC", "Greater Kansas City", "Kansas City Metro", "KC Metro"],
    cities: { MO: "Kansas City,Lee's Summit,Independence,Liberty,Blue Springs,North Kansas City,Raytown,Grandview,Gladstone,Belton,Raymore,Parkville,Riverside", KS: "Kansas City,Overland Park,Olathe,Lenexa,Shawnee,Leawood,Merriam,Mission,Prairie Village,Gardner,De Soto,Lansing,Leavenworth,Bonner Springs" },
  },
  {
    slug: "omaha",
    name: "Omaha area",
    states: ["NE", "IA"],
    aliases: ["Omaha", "Greater Omaha", "Omaha-Council Bluffs"],
    cities: { NE: "Omaha,Bellevue,Papillion,La Vista,Elkhorn,Gretna,Offutt AFB,Offutt Air Force Base", IA: "Council Bluffs" },
  },
  {
    slug: "des-moines",
    name: "Des Moines area",
    states: ["IA"],
    aliases: ["Des Moines", "Greater Des Moines", "DSM"],
    cities: { IA: "Des Moines,West Des Moines,Ankeny,Urbandale,Johnston,Waukee,Clive,Altoona,Grimes,Norwalk" },
  },
  {
    slug: "oklahoma-city",
    name: "Oklahoma City area",
    states: ["OK"],
    aliases: ["Oklahoma City", "OKC", "Greater Oklahoma City"],
    cities: { OK: "Oklahoma City,Edmond,Norman,Moore,Midwest City,Yukon,Mustang,Del City,Tinker AFB" },
  },
  {
    slug: "tulsa",
    name: "Tulsa area",
    states: ["OK"],
    aliases: ["Tulsa", "Greater Tulsa"],
    cities: { OK: "Tulsa,Broken Arrow,Owasso,Bixby,Jenks,Sand Springs,Sapulpa" },
  },
  {
    slug: "northwest-arkansas",
    name: "Northwest Arkansas",
    states: ["AR"],
    aliases: ["Northwest Arkansas", "NWA", "Bentonville"],
    cities: { AR: "Bentonville,Fayetteville,Rogers,Springdale,Bella Vista,Lowell,Siloam Springs,Centerton" },
  },
  {
    slug: "little-rock",
    name: "Little Rock area",
    states: ["AR"],
    aliases: ["Little Rock", "Central Arkansas"],
    cities: { AR: "Little Rock,North Little Rock,Conway,Benton,Bryant,Sherwood,Maumelle,Jacksonville" },
  },
  {
    slug: "new-orleans",
    name: "New Orleans area",
    states: ["LA"],
    aliases: ["New Orleans", "NOLA", "Greater New Orleans"],
    cities: { LA: "New Orleans,Metairie,Kenner,Slidell,Covington,Mandeville,Harvey,Marrero,Gretna,Chalmette" },
  },
  {
    slug: "baton-rouge",
    name: "Baton Rouge area",
    states: ["LA"],
    aliases: ["Baton Rouge"],
    cities: { LA: "Baton Rouge,Prairieville,Denham Springs,Gonzales,Zachary,Central" },
  },
  {
    slug: "nashville",
    name: "Nashville area",
    states: ["TN"],
    aliases: ["Nashville", "Greater Nashville", "Middle Tennessee", "Nashville Metro"],
    cities: { TN: "Nashville,Franklin,Brentwood,Murfreesboro,Smyrna,Hendersonville,Mount Juliet,Gallatin,Spring Hill,Lebanon,Columbia,La Vergne,Nolensville,Thompson's Station,Goodlettsville,Clarksville" },
  },
  {
    slug: "memphis",
    name: "Memphis area",
    states: ["TN", "MS", "AR"],
    aliases: ["Memphis", "Greater Memphis", "Mid-South"],
    cities: { TN: "Memphis,Germantown,Collierville,Bartlett,Cordova,Millington,Arlington", MS: "Southaven,Olive Branch,Horn Lake", AR: "West Memphis" },
  },
  {
    slug: "knoxville",
    name: "Knoxville area",
    states: ["TN"],
    aliases: ["Knoxville", "East Tennessee"],
    cities: { TN: "Knoxville,Oak Ridge,Maryville,Farragut,Alcoa,Lenoir City" },
  },
  {
    slug: "chattanooga",
    name: "Chattanooga area",
    states: ["TN", "GA"],
    aliases: ["Chattanooga"],
    cities: { TN: "Chattanooga,Cleveland,Hixson,Ooltewah,East Ridge", GA: "Dalton,Fort Oglethorpe" },
  },
  {
    slug: "louisville",
    name: "Louisville area",
    states: ["KY", "IN"],
    aliases: ["Louisville", "Greater Louisville", "Kentuckiana"],
    cities: { KY: "Louisville,Jeffersontown,St. Matthews,Shively,Shepherdsville,Fort Knox", IN: "Jeffersonville,New Albany,Clarksville" },
  },
  {
    slug: "lexington",
    name: "Lexington, KY area",
    states: ["KY"],
    aliases: ["Lexington KY", "Bluegrass"],
    cities: { KY: "Lexington,Georgetown,Nicholasville,Richmond,Winchester" },
  },
  {
    slug: "huntsville",
    name: "Huntsville area",
    states: ["AL"],
    aliases: ["Huntsville", "Rocket City", "Redstone Arsenal"],
    cities: { AL: "Huntsville,Madison,Decatur,Athens,Redstone Arsenal" },
  },
  {
    slug: "birmingham",
    name: "Birmingham, AL area",
    states: ["AL"],
    aliases: ["Birmingham AL", "Greater Birmingham"],
    cities: { AL: "Birmingham,Hoover,Vestavia Hills,Homewood,Alabaster,Bessemer,Mountain Brook,Trussville,Pelham" },
  },
  {
    slug: "honolulu",
    name: "Honolulu area",
    states: ["HI"],
    aliases: ["Honolulu", "Oahu"],
    cities: { HI: "Honolulu,Pearl City,Kailua,Kapolei,Kaneohe,Waipahu,Mililani,Ewa Beach,Pearl Harbor,Aiea" },
  },
  {
    slug: "anchorage",
    name: "Anchorage area",
    states: ["AK"],
    aliases: ["Anchorage"],
    cities: { AK: "Anchorage,Wasilla,Palmer,Eagle River,Joint Base Elmendorf-Richardson" },
  },
  {
    slug: "albany",
    name: "Albany / Capital Region",
    states: ["NY"],
    aliases: ["Albany", "Capital Region", "Capital District", "Albany-Schenectady-Troy"],
    cities: { NY: "Albany,Schenectady,Troy,Saratoga Springs,Clifton Park,Colonie,Latham,Malta,Niskayuna,Guilderland,Rensselaer,Cohoes" },
  },
  {
    slug: "rochester-ny",
    name: "Rochester, NY area",
    states: ["NY"],
    aliases: ["Rochester NY", "Greater Rochester"],
    cities: { NY: "Rochester,Henrietta,Pittsford,Webster,Greece,Irondequoit,Brighton,Fairport,Penfield,Victor" },
  },
  {
    slug: "buffalo",
    name: "Buffalo area",
    states: ["NY"],
    aliases: ["Buffalo", "Western New York", "WNY", "Buffalo-Niagara"],
    cities: { NY: "Buffalo,Amherst,Cheektowaga,Tonawanda,Niagara Falls,West Seneca,Williamsville,Orchard Park,Lancaster,Hamburg,Lockport,Getzville" },
  },
  {
    slug: "syracuse",
    name: "Syracuse area",
    states: ["NY"],
    aliases: ["Syracuse", "Central New York", "CNY"],
    cities: { NY: "Syracuse,Liverpool,Cicero,Clay,Baldwinsville,East Syracuse,Fayetteville,Camillus" },
  },
  {
    slug: "portland-me",
    name: "Portland, ME area",
    states: ["ME"],
    aliases: ["Portland Maine", "Southern Maine", "Greater Portland Maine"],
    cities: { ME: "Portland,South Portland,Westbrook,Scarborough,Falmouth,Saco,Biddeford,Brunswick" },
  },
  {
    slug: "burlington-vt",
    name: "Burlington, VT area",
    states: ["VT"],
    aliases: ["Burlington VT", "Chittenden County"],
    cities: { VT: "Burlington,South Burlington,Essex Junction,Essex,Colchester,Winooski,Williston" },
  },
  {
    slug: "san-luis-obispo",
    name: "San Luis Obispo area",
    states: ["CA"],
    aliases: ["San Luis Obispo", "SLO", "Central Coast"],
    cities: { CA: "San Luis Obispo,Paso Robles,Atascadero,Arroyo Grande,Pismo Beach,Grover Beach" },
  },
  {
    slug: "monterey",
    name: "Monterey Bay area",
    states: ["CA"],
    aliases: ["Monterey", "Monterey Bay", "Salinas"],
    cities: { CA: "Salinas,Monterey,Seaside,Marina,Pacific Grove,Carmel-by-the-Sea" },
  },
  {
    slug: "stockton-modesto",
    name: "Stockton-Modesto area",
    states: ["CA"],
    aliases: ["Stockton", "Modesto", "San Joaquin Valley"],
    cities: { CA: "Stockton,Modesto,Tracy,Manteca,Lodi,Turlock,Ceres,Lathrop,Riverbank,Oakdale" },
  },
  {
    slug: "bakersfield",
    name: "Bakersfield area",
    states: ["CA"],
    aliases: ["Bakersfield", "Kern County"],
    cities: { CA: "Bakersfield,Delano,Ridgecrest,Tehachapi,China Lake,Edwards AFB,Edwards Air Force Base,Mojave" },
  },
  {
    slug: "eugene",
    name: "Eugene area",
    states: ["OR"],
    aliases: ["Eugene", "Eugene-Springfield"],
    cities: { OR: "Eugene,Springfield" },
  },
  {
    slug: "salem-or",
    name: "Salem, OR area",
    states: ["OR"],
    aliases: ["Salem Oregon"],
    cities: { OR: "Salem,Keizer" },
  },
  {
    slug: "olympia",
    name: "Olympia area",
    states: ["WA"],
    aliases: ["Olympia", "Thurston County"],
    cities: { WA: "Olympia,Lacey,Tumwater" },
  },
  {
    slug: "kitsap",
    name: "Kitsap / Bremerton",
    states: ["WA"],
    aliases: ["Kitsap", "Bremerton", "Kitsap County"],
    cities: { WA: "Bremerton,Silverdale,Port Orchard,Poulsbo,Bainbridge Island" },
  },
  {
    slug: "tri-cities-wa",
    name: "Tri-Cities, WA",
    states: ["WA"],
    aliases: ["Tri-Cities WA", "Tri-Cities Washington"],
    cities: { WA: "Kennewick,Pasco,Richland,West Richland" },
  },
  {
    slug: "montgomery",
    name: "Montgomery area",
    states: ["AL"],
    aliases: ["Montgomery AL"],
    cities: { AL: "Montgomery,Prattville,Maxwell AFB" },
  },
  {
    slug: "savannah",
    name: "Savannah area",
    states: ["GA"],
    aliases: ["Savannah"],
    cities: { GA: "Savannah,Pooler,Richmond Hill" },
  },
  {
    slug: "augusta",
    name: "Augusta area",
    states: ["GA", "SC"],
    aliases: ["Augusta GA", "CSRA"],
    cities: { GA: "Augusta,Evans,Martinez,Grovetown,Fort Gordon,Fort Eisenhower", SC: "Aiken,North Augusta" },
  },
  {
    slug: "sarasota",
    name: "Sarasota-Bradenton",
    states: ["FL"],
    aliases: ["Sarasota", "Sarasota-Bradenton", "Lakewood Ranch"],
    cities: { FL: "Sarasota,Bradenton,Lakewood Ranch,Venice,North Port,Palmetto" },
  },
  {
    slug: "fort-myers",
    name: "Fort Myers / Naples",
    states: ["FL"],
    aliases: ["Fort Myers", "Southwest Florida", "SWFL"],
    cities: { FL: "Fort Myers,Cape Coral,Naples,Bonita Springs,Estero,Lehigh Acres" },
  },
  {
    slug: "space-coast",
    name: "Space Coast",
    states: ["FL"],
    aliases: ["Space Coast", "Brevard County", "Melbourne FL"],
    cities: { FL: "Melbourne,Palm Bay,Titusville,Cocoa,Cocoa Beach,Rockledge,Merritt Island,Cape Canaveral,Satellite Beach,West Melbourne,Viera,Kennedy Space Center" },
  },
  {
    slug: "tallahassee",
    name: "Tallahassee area",
    states: ["FL"],
    aliases: ["Tallahassee"],
    cities: { FL: "Tallahassee" },
  },
  {
    slug: "gainesville",
    name: "Gainesville, FL area",
    states: ["FL"],
    aliases: ["Gainesville FL"],
    cities: { FL: "Gainesville,Alachua" },
  },
  {
    slug: "pensacola",
    name: "Pensacola area",
    states: ["FL"],
    aliases: ["Pensacola", "Emerald Coast"],
    cities: { FL: "Pensacola,Fort Walton Beach,Destin,Niceville,Crestview,Navarre,Eglin AFB,Hurlburt Field" },
  },
  {
    slug: "champaign",
    name: "Champaign-Urbana",
    states: ["IL"],
    aliases: ["Champaign-Urbana", "Champaign Urbana", "Chambana"],
    cities: { IL: "Champaign,Urbana,Savoy,Rantoul" },
  },
  {
    slug: "rochester-mn",
    name: "Rochester, MN area",
    states: ["MN"],
    aliases: ["Rochester MN"],
    cities: { MN: "Rochester,Byron,Stewartville" },
  },
  {
    slug: "sioux-falls",
    name: "Sioux Falls area",
    states: ["SD"],
    aliases: ["Sioux Falls"],
    cities: { SD: "Sioux Falls,Brandon,Harrisburg,Tea" },
  },
  {
    slug: "fargo",
    name: "Fargo-Moorhead",
    states: ["ND", "MN"],
    aliases: ["Fargo", "Fargo-Moorhead"],
    cities: { ND: "Fargo,West Fargo", MN: "Moorhead" },
  },
  {
    slug: "wichita",
    name: "Wichita area",
    states: ["KS"],
    aliases: ["Wichita"],
    cities: { KS: "Wichita,Derby,Andover,Haysville,McConnell AFB" },
  },
  {
    slug: "lincoln",
    name: "Lincoln, NE area",
    states: ["NE"],
    aliases: ["Lincoln NE"],
    cities: { NE: "Lincoln" },
  },
];

/** Cities not in any metro above, by state. */
export const OTHER_CITIES: Record<string, string> = {
  AL: "Mobile,Tuscaloosa,Auburn,Dothan,Florence,Gadsden,Opelika,Enterprise",
  AK: "Fairbanks,Juneau,Ketchikan",
  AZ: "Flagstaff,Yuma,Prescott,Prescott Valley,Lake Havasu City,Sierra Vista,Bullhead City,Kingman",
  AR: "Fort Smith,Jonesboro,Pine Bluff,Hot Springs",
  CA: "Chico,Redding,Visalia,Tulare,Hanford,Merced,El Centro,Eureka,Yuba City,Porterville,Truckee,South Lake Tahoe",
  CO: "Pueblo,Grand Junction,Durango,Aspen,Vail,Steamboat Springs",
  CT: "Norwich,New London,Groton,Storrs",
  DE: "Georgetown,Lewes",
  FL: "Lakeland,Winter Haven,Ocala,Deltona,Daytona Beach,Port St. Lucie,Fort Pierce,Vero Beach,Stuart,Palm Coast,Panama City,Key West,Sebring,The Villages,DeLand,Ormond Beach,Port Orange,New Smyrna Beach",
  GA: "Columbus,Athens,Macon,Albany,Warner Robins,Valdosta,Rome,Gainesville,Brunswick,Statesboro,Carrollton",
  HI: "Hilo,Kahului,Kihei,Lahaina,Kailua-Kona,Lihue",
  ID: "Idaho Falls,Pocatello,Twin Falls,Lewiston,Moscow,Rexburg",
  IL: "Rockford,Peoria,Springfield,Bloomington,Normal,Decatur,Carbondale,DeKalb,Quincy,Danville,Moline,Rock Island,Kankakee",
  IN: "Fort Wayne,Evansville,South Bend,Bloomington,West Lafayette,Lafayette,Muncie,Terre Haute,Kokomo,Mishawaka,Elkhart,Columbus,Richmond,Goshen",
  IA: "Cedar Rapids,Iowa City,Coralville,Davenport,Bettendorf,Sioux City,Waterloo,Cedar Falls,Ames,Dubuque,Marion",
  KS: "Topeka,Lawrence,Manhattan,Salina,Hutchinson,Emporia,Fort Riley",
  KY: "Bowling Green,Owensboro,Paducah,Elizabethtown,Frankfort,Hopkinsville,Fort Campbell",
  LA: "Shreveport,Bossier City,Lafayette,Lake Charles,Monroe,Alexandria,Houma,Hammond,Ruston,Barksdale AFB",
  ME: "Bangor,Lewiston,Auburn,Augusta,Orono",
  MD: "Hagerstown,Salisbury,Cumberland,Ocean City,Lexington Park,Patuxent River",
  MA: "Springfield,Chicopee,Holyoke,Westfield,Pittsfield,Amherst,Northampton,Barnstable,Hyannis,Falmouth",
  MI: "Flint,Kalamazoo,Portage,Battle Creek,Saginaw,Midland,Bay City,Jackson,Muskegon,Traverse City,Marquette,Houghton,Mount Pleasant,Port Huron",
  MN: "Duluth,St. Cloud,Mankato,Winona",
  MS: "Jackson,Gulfport,Biloxi,Hattiesburg,Oxford,Starkville,Tupelo,Meridian,Madison,Ridgeland,Brandon,Pascagoula,Columbus AFB,Keesler AFB",
  MO: "Springfield,Columbia,Jefferson City,Joplin,St. Joseph,Cape Girardeau,Rolla,Fort Leonard Wood",
  MT: "Billings,Missoula,Bozeman,Great Falls,Helena,Butte,Kalispell,Whitefish,Belgrade",
  NE: "Grand Island,Kearney,Norfolk,North Platte",
  NV: "Elko,Fallon",
  NH: "Keene,Lebanon,Hanover,Laconia",
  NJ: "Atlantic City,Egg Harbor Township,Ocean City,Millville,Bridgeton,Mount Holly,Joint Base McGuire-Dix-Lakehurst,Fort Dix",
  NM: "Las Cruces,Santa Fe,Los Alamos,Roswell,Farmington,Clovis,Hobbs,White Sands Missile Range,Alamogordo",
  NY: "Ithaca,Binghamton,Utica,Poughkeepsie,Kingston,Newburgh,Middletown,Fishkill,Beacon,Elmira,Corning,Jamestown,Watertown,Plattsburgh,Glens Falls,Oneonta,Cortland,Oswego,Fort Drum,West Point,Stony Brook,Riverhead,Southampton,Yorktown Heights",
  NC: "Asheville,Wilmington,Fayetteville,Greenville,Jacksonville,Boone,Hickory,Rocky Mount,Wilson,Goldsboro,New Bern,Fort Bragg,Fort Liberty,Camp Lejeune,Salisbury,Statesville,Sanford",
  ND: "Bismarck,Grand Forks,Minot,Mandan,Williston",
  OH: "Canton,Youngstown,Springfield,Mansfield,Lima,Athens,Oxford,Sandusky,Zanesville,Findlay,Wooster,Marion,Chillicothe",
  OK: "Lawton,Stillwater,Enid,Muskogee,Bartlesville,Shawnee,Ardmore,Fort Sill",
  OR: "Bend,Medford,Corvallis,Albany,Grants Pass,Redmond,Klamath Falls,Ashland,Roseburg,Pendleton",
  PA: "Harrisburg,Mechanicsburg,Camp Hill,Hershey,Carlisle,Lancaster,York,Reading,Scranton,Wilkes-Barre,Erie,State College,Altoona,Johnstown,Williamsport,Lebanon,Pottsville,Hazleton,Stroudsburg,Chambersburg,Gettysburg,New Cumberland",
  RI: "Westerly,Middletown,Portsmouth",
  SC: "Myrtle Beach,Florence,Hilton Head Island,Beaufort,Sumter,Orangeburg,Clemson,Bluffton,Conway",
  SD: "Rapid City,Aberdeen,Brookings,Watertown,Vermillion",
  TN: "Jackson,Johnson City,Kingsport,Bristol,Cookeville,Tullahoma,Morristown",
  TX: "Corpus Christi,Lubbock,Laredo,Amarillo,Brownsville,McAllen,Edinburg,Mission,Pharr,Harlingen,Killeen,Temple,Belton,Waco,Midland,Odessa,Beaumont,Port Arthur,Abilene,Tyler,College Station,Bryan,Wichita Falls,Longview,Victoria,San Angelo,Texarkana,Sherman,Nacogdoches,Huntsville,Fort Hood,Fort Cavazos,Del Rio,Eagle Pass,Kingsville,Weslaco",
  UT: "St. George,Logan,Cedar City,Park City,Heber City,Moab",
  VT: "Montpelier,Rutland,Brattleboro,Middlebury",
  VA: "Charlottesville,Blacksburg,Roanoke,Lynchburg,Harrisonburg,Winchester,Staunton,Danville,Bristol,Christiansburg,Radford,Culpeper,Warrenton,Dahlgren,Quantico",
  WA: "Bellingham,Yakima,Wenatchee,Walla Walla,Mount Vernon,Pullman,Ellensburg,Oak Harbor,Longview,Anacortes,Port Angeles,Whidbey Island",
  WV: "Charleston,Huntington,Morgantown,Parkersburg,Wheeling,Fairmont,Clarksburg,Beckley",
  WI: "Green Bay,Appleton,Oshkosh,Eau Claire,Janesville,La Crosse,Sheboygan,Wausau,Fond du Lac,Beloit,Stevens Point,Neenah,Manitowoc",
  WY: "Cheyenne,Casper,Laramie,Gillette,Rock Springs,Sheridan,Jackson",
  DC: "",
};
